"""Alembic environment — wired to the async engine and the naming-convention
metadata so a generated migration and the running application never disagree
about a constraint name (database.md §2, §17 R-1).

No revision exists yet: no ORM models have been declared (this bootstrap task
deliberately does not implement any — A64-006 scope). The first module to
declare a table is also the first to run `alembic revision --autogenerate`.
"""

import asyncio
from logging.config import fileConfig
from typing import Any, Literal

from alembic.autogenerate.api import AutogenContext
from sqlalchemy import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config
from sqlalchemy.types import TypeEngine

from alembic import context
from app.config.settings import get_settings
from app.database.base import Base

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Single source of truth for "what tables exist" — every module's Base
# metadata is expected to merge into this one target (database.md §3,
# one schema namespace per module, one MetaData naming convention).
target_metadata = Base.metadata


def render_item(type_: str, obj: object, autogen_context: AutogenContext) -> str | Literal[False]:
    """Without this, a migration referencing a project-defined column type
    (`app.database.types.UtcDateTime`, and any future one) omits the
    import that makes the generated file actually importable — Alembic's
    default renderer only knows how to import `sqlalchemy`'s own types,
    and silently emits a bare `UtcDateTime(...)` with nothing defining
    `UtcDateTime` in the file. Verified against a real generated migration
    during A64-009 (see the task's summary) — this is not a theoretical
    gap.

    Generic over every current and future type: anything defined under
    `app.*` gets its import rendered automatically, rather than requiring
    a new branch here each time a module adds a column type.
    """
    if type_ == "type" and isinstance(obj, TypeEngine):
        module = type(obj).__module__
        if module.startswith("app."):
            name = type(obj).__name__
            autogen_context.imports.add(f"from {module} import {name}")
            return f"{name}()"
    return False


def _configure_common() -> dict[str, Any]:
    return {
        "target_metadata": target_metadata,
        "render_item": render_item,
        # Both default to False in Alembic — deliberately turned on here.
        # Without `compare_type`, changing a column's declared type (an
        # `Integer` becoming a `BigInteger`, e.g.) produces an *empty*
        # autogenerated migration: Alembic silently agrees the schema
        # already matches. `compare_server_default` closes the same gap
        # for `server_default=func.now()` (`TimestampMixin`) and other
        # database-enforced defaults. "Autogeneration must work correctly"
        # (this task) means a real change is never autogenerated as a
        # no-op.
        "compare_type": True,
        "compare_server_default": True,
    }


def _dsn() -> str:
    # Settings, not alembic.ini, own the DSN — see alembic.ini's comment.
    # Migrations always run against the primary; there is no replica case
    # for DDL (database.md §13.2 replica routing is a read-only concern).
    # `.get_secret_value()` is required: `dsn` is a `SecretStr` (it embeds
    # a password), and passing the wrapper itself where Alembic/SQLAlchemy
    # expect a plain string silently stringifies to "**********" instead
    # of connecting — a bug that mypy could not catch because `alembic/`
    # is excluded from the strict configuration (pyproject.toml).
    return get_settings().postgres.dsn.get_secret_value()


def run_migrations_offline() -> None:
    """Emit SQL to stdout without a live database connection."""
    context.configure(
        url=_dsn(),
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        **_configure_common(),
    )
    with context.begin_transaction():
        context.run_migrations()


def _run_migrations_sync(connection: Connection) -> None:
    context.configure(connection=connection, **_configure_common())
    with context.begin_transaction():
        context.run_migrations()


async def run_migrations_online() -> None:
    """Emit SQL against a live database connection, via the async engine."""
    configuration = config.get_section(config.config_ini_section) or {}
    configuration["sqlalchemy.url"] = _dsn()

    connectable = async_engine_from_config(
        configuration,
        prefix="sqlalchemy.",
        future=True,
    )

    async with connectable.connect() as connection:
        await connection.run_sync(_run_migrations_sync)

    await connectable.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    asyncio.run(run_migrations_online())
