"""`OpaqueTokenService` — generate, hash, verify. The platform's one
implementation of DB-24.

Extracted from `RefreshTokenService` by A64-011.6, which needed exactly
the same three operations for email verification tokens. That extraction
is not tidiness: database.md DB-24 names **four** kinds of value with
identical requirements —

> Refresh tokens, reset tokens, verification tokens and ticket values are
> generated by the platform from a cryptographic random source.

— and a second, independently-written copy of "draw randomness, hash it,
compare it" is how one of the four ends up drawing from `random`, or
comparing with `==`, or hashing a hex rendering. Two callers exist today
and A64-011.7's password reset is the third; the fourth is AD-09's
WebSocket ticket.

## Why SHA-256 and not Argon2id — DB-24

The platform hashes passwords with Argon2id and these with SHA-256, and
the doc is explicit that the difference is reasoning rather than
sloppiness:

> Argon2id's cost exists to defeat brute force against a small guessable
> space. A 256-bit random token has no such space — an attacker with the
> hash gains nothing from any amount of computation. Applying Argon2id to
> refresh tokens would put tens of milliseconds of deliberate work on the
> token-refresh path, which every connected client executes repeatedly, in
> exchange for no additional security. Applying SHA-256 to passwords would
> be a serious defect. Same operation, opposite reasoning, and getting
> them backwards is common.

The load-bearing premise is *256 bits from a CSPRNG*, which is why
`entropy_bytes` has a floor rather than a default someone can lower.

No salt, and that is deliberate too. A salt defends against precomputed
tables over a guessable space; there is no such space here, and an
unsalted digest is what makes the hash a *lookup key* — a verification
looks up one row by digest rather than fetching candidates and comparing
each. A salted scheme would turn one indexed lookup into a scan.
"""

import hashlib
import hmac
import secrets

from app.config.settings import REFRESH_TOKEN_MIN_ENTROPY_BYTES


class OpaqueTokenService:
    """Stateless. Holds one number and no knowledge of what the tokens
    mean — `SessionService` and `EmailVerificationService` decide that."""

    def __init__(self, entropy_bytes: int = REFRESH_TOKEN_MIN_ENTROPY_BYTES) -> None:
        if entropy_bytes < REFRESH_TOKEN_MIN_ENTROPY_BYTES:
            # Belt and braces: the settings classes already enforce this
            # with a `ge=` bound, but this class is constructible from a
            # plain int and the floor is the premise DB-24's whole
            # argument rests on. A constructor that silently accepted 8
            # bytes would make SHA-256 the wrong choice without anything
            # failing.
            raise ValueError(
                f"entropy_bytes must be at least {REFRESH_TOKEN_MIN_ENTROPY_BYTES} "
                "— below 256 bits, hashing these with SHA-256 rather than "
                "Argon2id stops being sound (DB-24)"
            )
        self._entropy_bytes = entropy_bytes

    def generate(self) -> str:
        """A new, unguessable token.

        `secrets.token_urlsafe`, not `random`, not `uuid4`, not
        `os.urandom` formatted by hand:

        - `random` is a Mersenne Twister seeded from the clock, and
          observing a few outputs lets an attacker predict every
          subsequent one. Not a failure that shows up in testing; one
          that shows up in an incident report.
        - `uuid4` carries 122 bits, not 256, and six of them are fixed
          version/variant markers. Under the threshold DB-24 depends on.
        - `secrets` draws from the OS CSPRNG, which is what
          "cryptographically secure" means here.

        URL-safe base64, so the token survives a `Set-Cookie` header, a
        query string and a JSON body without escaping — and that matters
        more for a verification token than a refresh token, because this
        one goes in a **link**. A token needing percent-encoding is a
        token that eventually gets compared in two different encodings.

        `token_urlsafe(n)` returns roughly `4n/3` characters carrying `8n`
        bits; at 32 bytes that is 43 characters and 256 bits.
        """
        return secrets.token_urlsafe(self._entropy_bytes)

    def hash(self, token: str) -> bytes:
        """The digest that gets stored — DB-24.

        Returns `bytes`, not a hex string, because the columns are
        `bytea` and because a hex rendering is a second representation of
        the same value that something will eventually compare against the
        first. The bug that costs a day is `"a1b2..." != b"\\xa1\\xb2..."`
        silently never matching.

        Deterministic and unsalted, so this doubles as the lookup key —
        see this module's docstring.
        """
        return hashlib.sha256(token.encode("utf-8")).digest()

    def verify(self, token: str, expected_hash: bytes) -> bool:
        """Whether `token` is the one `expected_hash` was made from.

        `hmac.compare_digest`, never `==`. The comparison is of two
        digests rather than two secrets, so the timing leak is weaker
        than it would be on a password — but "weaker" is not "absent",
        and the cost of doing it right is a function call. Writing `==` in
        a credential path is also the kind of thing that gets copied into
        a place where it does matter.

        Returns a plain `bool` rather than raising: a token that does not
        match is an ordinary outcome, and every caller has to treat it
        identically to "no such row" anyway.
        """
        return hmac.compare_digest(self.hash(token), expected_hash)
