"""The read shapes `users` publishes.

These live in `public/` rather than in `presentation/schemas/` because
they are now consumed in two directions: this module's own router renders
them, and `auth` receives them across a module boundary (BR-2: a
`public/` port is defined in terms of `public/` DTOs only). Defining them
here and importing downward is what keeps `application/` — which returns
them from the published port — from having to import `presentation/`,
which would be an upward import and exactly the layering inversion
architecture.md §8 forbids.

A64-010 defined them in `presentation/schemas/user.py`; that module now
imports them from here, so the names every existing caller uses are
unchanged.

Neither carries `password_hash`, and neither ever will — see
`app/modules/auth/` for who owns credentials.
"""

from datetime import datetime
from uuid import UUID

from app.core.dto import BaseResponseDTO
from app.core.enums import Locale
from app.modules.users.domain.preferences import AnimationSpeed, BoardTheme, PieceSet
from app.modules.users.domain.visibility import VisibilityLevel


class AvatarReference(BaseResponseDTO):
    """Where a player's avatar is stored, and how stale a cached copy is.

    Published rather than kept private because three modules need it and
    none of them may reach into `users`' table: `avatars` writes it,
    `profiles` renders it, and both do so through ports.

    **Carries no URL, deliberately.** `object_key` is the object's address
    in whatever store the deployment uses, and turning it into something a
    browser can fetch is `StorageProvider.get_public_url`'s job. A DTO with
    a URL on it would mean the module that built it had to know the CDN
    hostname, which is exactly the coupling A64-012.2's "public URL must be
    generated by StorageProvider" forbids.
    """

    object_key: str | None
    """The stored original, or `None` when the player has no avatar. The
    thumbnail's key is *derived* from this one rather than stored beside
    it — see `avatars.domain.keys`."""

    version: int
    """Increments on every upload and every delete. Present even when
    `object_key` is `None`, because a client that cached the *previous*
    avatar needs the change signal precisely when the avatar has just been
    removed."""

    uploaded_at: datetime | None
    """`None` exactly when `object_key` is — a database CHECK enforces the
    pairing."""

    @property
    def is_set(self) -> bool:
        return self.object_key is not None


class ProfileVisibility(BaseResponseDTO):
    """Which *composed* parts of a public profile a consumer may render —
    A64-012.4.

    ## Why this crosses the boundary at all

    A privacy flag is applied wherever the data it governs is produced, and
    `users` does not produce all of it. It owns `country`, so it hides that
    field itself: `to_public_profile` returns `country=None` and no flag is
    published for it, exactly as `is_active` is applied inside `users` and
    never published. That is the strongest form — the consumer cannot render
    a hidden country because it never receives one.

    The other four govern data `users` does not own. Match statistics come
    from a statistics system, presence from a socket gateway, activity from
    match history. `users` cannot redact what it never holds, so it publishes
    the *decision* and the composing module applies it. UP-4 requires the
    enforcement to be server-side on every read path; this is what makes it
    server-side on the paths that run outside this module.

    ## Why this is never on the wire

    `PublicUserProfile` is an internal published DTO, not a response schema.
    `profiles` maps it field by field into `ProfileResponse`, and these flags
    are not among the fields it maps — so an anonymous caller sees
    `statistics: null` and cannot tell a player who hid their record from a
    platform that has not computed one yet.

    That ambiguity is the point. Publishing `statistics_hidden: true` would
    answer the question the setting exists to decline, in the same way
    publishing `is_active` would announce which accounts have been withdrawn.

    Every field is `True` for *visible*. No inverted spellings — see
    `users.domain.privacy` on why a `hide_*` beside a `show_*` is how a
    mapper ends up applying one backwards.
    """

    last_seen: VisibilityLevel
    """Who may see when this player was last online — A64-013.2.

    A `VisibilityLevel` rather than a boolean since the audience model
    arrived. The consumer does not compare it against a member: it calls
    `PrivacySettings.permits_*` through the composer, which is what keeps
    `FRIENDS` from being silently treated as `EVERYONE` at a call site.
    """

    statistics: bool
    """Whether a consumer may render the aggregate match record.

    **Not ratings.** A rating is public on this platform — it is what
    pairing is computed from and what leaderboards already publish, and
    UP-5 keeps rated results visible to the people they concern. See
    `PrivacySettings.show_statistics`.
    """

    online_status: VisibilityLevel
    """Who may see live presence. The setting database.md §491 names
    outright, and the one that made A64-013.2 widen the type."""

    activity: VisibilityLevel
    """Who may see recent activity — match history, an activity feed.
    Published ahead of the thing it governs, as `online_status` was before
    presence existed."""


class UserRead(BaseResponseDTO):
    """The full view of a user's own account.

    Includes `email`, which is the account holder's own address. There is
    no authorisation layer yet to distinguish "my profile" from "someone
    else's", so this shape is currently returned for *any* user id — a gap
    A64-011.2 must close by splitting a self view from a public one. It is
    recorded here as well as in the router because this is the type that
    would carry the leak.
    """

    id: UUID
    username: str
    email: str
    display_name: str | None
    bio: str | None
    """Added by A64-012.3. A64-012.1 created the column and never put it on
    the account holder's own view, so `GET /auth/me` could not show what
    `GET /profiles/{username}` showed about the same person."""

    country: str | None
    avatar: AvatarReference
    preferred_language: Locale
    timezone: str
    is_active: bool
    is_verified: bool
    created_at: datetime
    updated_at: datetime | None


class UserSummary(BaseResponseDTO):
    """The minimal public view — what a list, a search result, or a future
    match card needs. Deliberately excludes email, verification state and
    timestamps: a listing is the highest-volume read on any user table, and
    the fields it omits are the ones that would make it a privacy question
    rather than a rendering one.
    """

    id: UUID
    username: str
    display_name: str | None
    avatar: AvatarReference


class PublicUserProfile(BaseResponseDTO):
    """What a stranger may see — A64-012.1's `GET /profiles/{username}`.

    ## Why this is a third read shape rather than a field on `UserRead`

    `UserRead` carries `email`. It is the account holder's *own* view, and
    its docstring has flagged since A64-010 that returning it for an
    arbitrary user id is a gap. A public profile endpoint is precisely the
    caller that would turn that gap into a disclosure, and "remember not to
    render the email field" is not a control — it is a convention that
    holds until the first careless `model_dump()`.

    So `profiles` never receives an email. Not "receives one and drops it":
    the port that serves it returns *this* type, which has no such field,
    so the leak is unreachable rather than merely avoided. That is the same
    reasoning `users` already applies five times over in `public/ports.py`,
    where creating an account, reading a password hash, reading a profile,
    confirming an address and replacing a credential are five separately
    grantable capabilities rather than one wide service.

    `UserSummary` was considered and is too thin — it has no join date, no
    country, no bio, and widening it would degrade the listing shape whose
    whole value is what it omits.

    ## What is deliberately absent

    No `email`, no `password_hash`, no `is_verified`, no `timezone`, no
    `locked_until`, no `updated_at`.

    The last four are the interesting omissions, because none is a
    credential and each is a small disclosure that adds up. `is_verified`
    and `locked_until` are account *state*: publishing them tells an
    attacker which accounts are half-registered or currently being
    attacked. `timezone` narrows a player's physical location. `updated_at`
    reveals when somebody last touched their account, which is activity
    metadata a stranger has no claim to and which A64-012.1's constraints
    exclude under "online status".

    `is_active` is absent for a different reason: a deactivated account has
    no public profile at all, so the flag would be constant-true wherever
    it could be read. `ProfileService` enforces that rather than exposing
    it — see its `find_by_username`.
    """

    id: UUID
    """The player identifier — DM-06's `player_id`, the only reference that
    crosses a context boundary.

    A64-012.1's "never expose internal ids" means session ids, token ids
    and row identifiers of `auth`'s tables. This one is public by design:
    it is what a future match record, rating row or leaderboard entry
    refers to a player by, and a client that could not obtain it could not
    fetch anything about them.
    """

    username: str
    display_name: str | None
    avatar: AvatarReference
    country: str | None
    """ISO 3166-1 alpha-2, upper-cased.

    **`None` when the player has hidden it** (A64-012.4's `show_country`),
    and identical in every respect to `None` for a player who never set
    one — same type, same value, nothing to branch on. The redaction
    happens in `to_public_profile`, before this DTO is constructed, because
    `users` owns the column; a consumer cannot render a hidden country
    because it is never handed one.
    """

    preferred_language: Locale
    bio: str | None
    """Plain text, at most 500 characters, already trimmed and free of
    control and bidirectional characters (`validate_bio`). Not Markdown —
    a renderer must not interpret it."""

    created_at: datetime
    """The join date. Named `created_at` here to match every other DTO on
    the platform and rendered as `joined_at` on the wire, where it is the
    word a player understands — see `profiles`' response schema."""

    visibility: ProfileVisibility
    """What the consumer may render of the parts `users` does not own.

    Carried on the profile rather than fetched separately so a consumer
    cannot compose a view without it — there is no call that returns the
    identity and leaves the visibility behind, which is what stops a future
    read path from forgetting to ask. See `ProfileVisibility`.
    """


class OwnUserProfile(BaseResponseDTO):
    """What the account holder sees of their own profile — A64-012.3.

    ## Why a fourth read shape

    The three that exist all answer a different question, and none of them
    answers this one:

        UserRead           the account, email included — `GET /auth/me`
        UserSummary        a listing row
        PublicUserProfile  what a *stranger* sees — no timezone, no email

    An edit form needs every field it can write plus enough identity to
    render a header. Reusing `UserRead` would put an email address in the
    response to every profile edit, which nothing in an edit form needs.

    So: exactly the editable fields, plus the identity and avatar a header
    renders, plus nothing else.

    ## What A64-012.5 removed, and why

    `preferred_language` and `timezone` were here. They moved to
    `PreferencesView`, because they moved out of `ProfileEdits` — and a
    shape whose whole justification is "every field this endpoint can
    write" must not keep returning two it no longer can. Leaving them would
    have made this the second read of a value with one writer, which is the
    drift `PATCH /profile/preferences` exists to prevent.

    `GET /auth/me` still reports both on `UserRead`; that is the account
    view and a different question.

    **No `email`, no `is_verified`, no `is_active`, no `locked_until`.**
    Account state and credentials belong to `auth` and are already served
    by `GET /auth/me`; duplicating them here would give a profile endpoint
    a second, drifting copy of them.
    """

    id: UUID
    username: str
    """Read-only here. A64-012.3 excludes username changes deliberately —
    a rename has to record the old handle and enforce a reuse cooldown
    (UP-2/UP-3), which is a use case of its own. Returned so an edit form
    can render the handle it may not change."""

    display_name: str | None
    bio: str | None
    country: str | None

    avatar: AvatarReference
    created_at: datetime


class PrivacySettingsView(BaseResponseDTO):
    """The owner's view of their own privacy controls — A64-012.4.

    ## Why this is a fifth read shape rather than a field on `OwnUserProfile`

    Different audience and different lifetime. `OwnUserProfile` answers
    *what does my profile say* and is the response to a profile edit; this
    answers *who may see it*, and a settings screen loads it without
    touching a name or a biography. Folding them together would mean every
    profile edit response also restated five privacy flags, and every
    privacy change response also restated a biography — two shapes each
    carrying half of something they do not own.

    It is also the shape that must **not** appear anywhere public. There is
    no anonymous read path that returns this type, and the four flags a
    consumer genuinely needs are published separately as
    `ProfileVisibility` — a narrower type with no `show_country`, because
    that one is applied inside `users` and never travels.

    All five flags are `True` for *visible*, matching the domain and the
    wire exactly. See `users.domain.privacy` for the defaults and why
    `show_last_seen` is the one that is off.
    """

    show_country: bool
    show_statistics: bool

    last_seen: VisibilityLevel
    online_status: VisibilityLevel
    activity: VisibilityLevel


class GameplayPreferencesView(BaseResponseDTO):
    """How the board looks and behaves for one player — A64-012.5.

    Carries the domain enums themselves rather than plain strings, which is
    what makes a consumer's `preferences.gameplay.board_theme is
    BoardTheme.WOOD` a type-checked comparison instead of a spelling
    contest. The enums are published from `users.public` alongside this, as
    BR-2 requires of anything a published DTO is defined in terms of.
    """

    board_theme: BoardTheme
    piece_set: PieceSet
    confirm_move: bool
    show_coordinates: bool
    animation_speed: AnimationSpeed


class LocalePreferencesView(BaseResponseDTO):
    """The language a player reads and the timezone they see times in —
    A64-012.5.

    Both were fields on `UserRead` and `OwnUserProfile` before this task
    and are still on `UserRead`, which is `auth`'s account view. What
    changed is that this is now the only shape they can be *written*
    through: `ProfileEdits` no longer carries them, so there is one
    writable path rather than two.
    """

    preferred_language: Locale
    timezone: str
    """The IANA name, already validated by the `Timezone` value object —
    a plain `str` on the wire because that is what an IANA name is."""


class PreferencesView(BaseResponseDTO):
    """One player's personal settings, grouped — A64-012.5.

    ## Why the groups are nested rather than flattened

    The nesting is the contract, not presentation. A group is the unit the
    API patches, the unit the audit log records, and the unit `ui` and
    `notifications` arrive as — a flat shape would make each of those a
    convention maintained by hand, and adding `notifications` would mean
    prefixing a dozen field names and hoping nobody forgets.

    ## Why privacy is not one of the groups

    domain-model.md §7.1 lists privacy as a fourth preference group, and it
    is deliberately absent here. `PrivacySettingsView` is its own published
    shape behind its own port, because a preference decides what *you* see
    and a privacy flag decides what *strangers* see — merging them would
    let a component that may change a board theme also publish an account's
    activity. The design document is describing what a profile owns; this
    is describing what one write may reach.

    **Never public.** No anonymous read path returns this type or any part
    of it, and `PublicUserProfile` carries none of these fields. A64-012.5:
    "preferences are never exposed publicly."
    """

    gameplay: GameplayPreferencesView
    locale: LocalePreferencesView
