"""The read shapes `users` publishes.

These live in `public/` rather than in `presentation/schemas/` because
they are now consumed in two directions: this module's own router renders
them, and `auth` receives them across a module boundary (BR-2: a
`public/` port is defined in terms of `public/` DTOs only). Defining them
here and importing downward is what keeps `application/` — which returns
them from the published port — from having to import `presentation/`,
which would be an upward import and exactly the layering inversion
architecture.md §8 forbids.

A64-010 defined them in `presentation/schemas/user.py`; that module now
imports them from here, so the names every existing caller uses are
unchanged.

Neither carries `password_hash`, and neither ever will — see
`app/modules/auth/` for who owns credentials.
"""

from datetime import datetime
from uuid import UUID

from app.core.dto import BaseResponseDTO
from app.core.enums import Locale


class AvatarReference(BaseResponseDTO):
    """Where a player's avatar is stored, and how stale a cached copy is.

    Published rather than kept private because three modules need it and
    none of them may reach into `users`' table: `avatars` writes it,
    `profiles` renders it, and both do so through ports.

    **Carries no URL, deliberately.** `object_key` is the object's address
    in whatever store the deployment uses, and turning it into something a
    browser can fetch is `StorageProvider.get_public_url`'s job. A DTO with
    a URL on it would mean the module that built it had to know the CDN
    hostname, which is exactly the coupling A64-012.2's "public URL must be
    generated by StorageProvider" forbids.
    """

    object_key: str | None
    """The stored original, or `None` when the player has no avatar. The
    thumbnail's key is *derived* from this one rather than stored beside
    it — see `avatars.domain.keys`."""

    version: int
    """Increments on every upload and every delete. Present even when
    `object_key` is `None`, because a client that cached the *previous*
    avatar needs the change signal precisely when the avatar has just been
    removed."""

    uploaded_at: datetime | None
    """`None` exactly when `object_key` is — a database CHECK enforces the
    pairing."""

    @property
    def is_set(self) -> bool:
        return self.object_key is not None


class UserRead(BaseResponseDTO):
    """The full view of a user's own account.

    Includes `email`, which is the account holder's own address. There is
    no authorisation layer yet to distinguish "my profile" from "someone
    else's", so this shape is currently returned for *any* user id — a gap
    A64-011.2 must close by splitting a self view from a public one. It is
    recorded here as well as in the router because this is the type that
    would carry the leak.
    """

    id: UUID
    username: str
    email: str
    display_name: str | None
    bio: str | None
    """Added by A64-012.3. A64-012.1 created the column and never put it on
    the account holder's own view, so `GET /auth/me` could not show what
    `GET /profiles/{username}` showed about the same person."""

    country: str | None
    avatar: AvatarReference
    preferred_language: Locale
    timezone: str
    is_active: bool
    is_verified: bool
    created_at: datetime
    updated_at: datetime | None


class UserSummary(BaseResponseDTO):
    """The minimal public view — what a list, a search result, or a future
    match card needs. Deliberately excludes email, verification state and
    timestamps: a listing is the highest-volume read on any user table, and
    the fields it omits are the ones that would make it a privacy question
    rather than a rendering one.
    """

    id: UUID
    username: str
    display_name: str | None
    avatar: AvatarReference


class PublicUserProfile(BaseResponseDTO):
    """What a stranger may see — A64-012.1's `GET /profiles/{username}`.

    ## Why this is a third read shape rather than a field on `UserRead`

    `UserRead` carries `email`. It is the account holder's *own* view, and
    its docstring has flagged since A64-010 that returning it for an
    arbitrary user id is a gap. A public profile endpoint is precisely the
    caller that would turn that gap into a disclosure, and "remember not to
    render the email field" is not a control — it is a convention that
    holds until the first careless `model_dump()`.

    So `profiles` never receives an email. Not "receives one and drops it":
    the port that serves it returns *this* type, which has no such field,
    so the leak is unreachable rather than merely avoided. That is the same
    reasoning `users` already applies five times over in `public/ports.py`,
    where creating an account, reading a password hash, reading a profile,
    confirming an address and replacing a credential are five separately
    grantable capabilities rather than one wide service.

    `UserSummary` was considered and is too thin — it has no join date, no
    country, no bio, and widening it would degrade the listing shape whose
    whole value is what it omits.

    ## What is deliberately absent

    No `email`, no `password_hash`, no `is_verified`, no `timezone`, no
    `locked_until`, no `updated_at`.

    The last four are the interesting omissions, because none is a
    credential and each is a small disclosure that adds up. `is_verified`
    and `locked_until` are account *state*: publishing them tells an
    attacker which accounts are half-registered or currently being
    attacked. `timezone` narrows a player's physical location. `updated_at`
    reveals when somebody last touched their account, which is activity
    metadata a stranger has no claim to and which A64-012.1's constraints
    exclude under "online status".

    `is_active` is absent for a different reason: a deactivated account has
    no public profile at all, so the flag would be constant-true wherever
    it could be read. `ProfileService` enforces that rather than exposing
    it — see its `find_by_username`.
    """

    id: UUID
    """The player identifier — DM-06's `player_id`, the only reference that
    crosses a context boundary.

    A64-012.1's "never expose internal ids" means session ids, token ids
    and row identifiers of `auth`'s tables. This one is public by design:
    it is what a future match record, rating row or leaderboard entry
    refers to a player by, and a client that could not obtain it could not
    fetch anything about them.
    """

    username: str
    display_name: str | None
    avatar: AvatarReference
    country: str | None
    """ISO 3166-1 alpha-2, upper-cased. `None` until profile editing
    exists — no endpoint writes it yet."""

    preferred_language: Locale
    bio: str | None
    """Plain text, at most 500 characters, already trimmed and free of
    control and bidirectional characters (`validate_bio`). Not Markdown —
    a renderer must not interpret it."""

    created_at: datetime
    """The join date. Named `created_at` here to match every other DTO on
    the platform and rendered as `joined_at` on the wire, where it is the
    word a player understands — see `profiles`' response schema."""


class OwnUserProfile(BaseResponseDTO):
    """What the account holder sees of their own profile — A64-012.3.

    ## Why a fourth read shape

    The three that exist all answer a different question, and none of them
    answers this one:

        UserRead           the account, email included — `GET /auth/me`
        UserSummary        a listing row
        PublicUserProfile  what a *stranger* sees — no timezone, no email

    An edit form needs every field it can write plus enough identity to
    render a header, and it needs `timezone`, which `PublicUserProfile`
    deliberately omits because publishing it narrows a player's physical
    location to anyone who asks. Widening the public shape to serve the
    owner would leak that to everybody; reusing `UserRead` would put an
    email address in the response to every profile edit, which nothing in
    an edit form needs.

    So: exactly the five editable fields, plus the identity and avatar a
    header renders, plus nothing else.

    **No `email`, no `is_verified`, no `is_active`, no `locked_until`.**
    Account state and credentials belong to `auth` and are already served
    by `GET /auth/me`; duplicating them here would give a profile endpoint
    a second, drifting copy of them.
    """

    id: UUID
    username: str
    """Read-only here. A64-012.3 excludes username changes deliberately —
    a rename has to record the old handle and enforce a reuse cooldown
    (UP-2/UP-3), which is a use case of its own. Returned so an edit form
    can render the handle it may not change."""

    display_name: str | None
    bio: str | None
    country: str | None
    preferred_language: Locale
    timezone: str

    avatar: AvatarReference
    created_at: datetime
