"""Object storage — the port and its vocabulary. No filesystem, no S3, no
FastAPI.

Framework-free by the same rule that keeps `clock.py` and `rate_limiting.py`
here (dependency-injection.md §3.2). What lives in this module is *what an
object store is*; `app/storage/local.py` knows how to be one on a disk, and
a future `S3StorageProvider` knows how to be one in a bucket. Neither knows
about the other, and no application service knows about either.

That is the requirement A64-012.2 states as "business logic must NEVER
depend on local storage implementation", and it is the reason this file
exists rather than `AvatarService` calling `pathlib` directly.

## The four operations, and why there are only four

`save`, `delete`, `exists`, `get_public_url`. Every object store on the
shortlist — S3, R2, MinIO, GCS — supports all four natively, which is what
makes the port implementable without emulation.

Deliberately **no** `read`/`download`. Nothing on this platform reads an
object back through the application: avatars are served to browsers
directly by the store (or by a CDN in front of it), and routing image bytes
through the API would put a Python process on the hot path of every avatar
render for no benefit. A method with no caller is one an implementation has
to get right anyway, so it is absent.

Deliberately **no** `list`. Enumerating a prefix is an expensive operation
on every real object store, and the one job it would serve here —
finding orphaned files — is better done by the caller never creating them.
See `AvatarService.replace` on how deletion ordering achieves that.

## Keys, not paths

A `str` key like `avatars/{user_id}/{uuid}.webp` is the whole address of an
object. It is **not** a filesystem path and must never be treated as one by
a caller: the local provider maps it onto a directory, and an S3 provider
maps it onto a bucket key, and neither mapping is a caller's business.

`get_public_url` is the only sanctioned way to turn a key into something a
client can fetch. A caller that concatenates a base URL with a key has
hardcoded one provider's URL scheme, which is exactly the coupling
A64-012.2's "public URL must be generated by StorageProvider" forbids.
"""

from typing import Protocol

from app.core.exceptions import PermanentInfrastructureError, TransientInfrastructureError

#: The separator inside an object key. Always `/`, on every provider and
#: every operating system.
#:
#: Not `os.sep`. A key is a *store* address, not a path, and a key written
#: on Windows must resolve to the same object as one written on Linux —
#: which is exactly what `os.sep` would break, silently, on the day
#: somebody develops on a different machine from the one that uploaded.
KEY_SEPARATOR = "/"


class StorageError(PermanentInfrastructureError):
    """A store rejected an operation and retrying will not help.

    On the platform hierarchy (services.md §7.1) rather than a parallel
    one, so `app/api/exception_handlers.py` maps it to a `500` by MRO walk
    with no per-module wiring. Permanent rather than transient: a
    misconfigured bucket, an unwritable directory or a refused permission
    does not resolve on its own, and a retry loop against one is how a
    single misconfiguration becomes a load test.

    A store that is *momentarily* unavailable — a network blip reaching S3
    — is a `TransientInfrastructureError` and is imported here so an
    implementation has both in scope without reaching for `core.exceptions`
    directly.
    """


class StorageProvider(Protocol):
    """Reads and writes immutable binary objects, addressed by key.

    A `Protocol`, not an ABC, so a provider is any object with these four
    methods — a test double included — and no implementation inherits from
    anything this platform owns.

    ## Objects are immutable; keys are never reused

    Nothing here updates an object in place, and that is a contract rather
    than an omission. `save` to an existing key is permitted to overwrite,
    but no caller on this platform does it: a new avatar gets a new random
    key and the old one is deleted afterwards.

    That convention buys two things at once. Caches and CDNs may treat any
    key as permanently immutable, which is what makes a long `max-age`
    safe. And a failed upload cannot corrupt the object a player currently
    has, because it was never writing to it.

    ## Every method may raise `StorageError`

    Providers translate their own failures — `OSError`, a boto exception, a
    404 from an API — at this boundary, so nothing above ever catches a
    driver type (services.md §7.2). `delete` and `exists` are the two that
    must *not* raise for the ordinary case of a missing object; see each.
    """

    async def save(self, key: str, data: bytes, *, content_type: str) -> None:
        """Writes `data` at `key`, creating any structure the key implies.

        Overwrites an existing object at the same key. No caller on this
        platform relies on that — see this class's docstring — but a store
        that refused would make retrying a partially-failed upload
        impossible.

        `content_type` is stored as object metadata where the provider
        supports it, because it is what the store sends as the
        `Content-Type` header when a browser fetches the object. Getting it
        wrong means an image downloaded rather than rendered. It is a
        required keyword rather than an optional one so that no caller
        forgets it and discovers the consequence in a browser.

        Raises `StorageError` if the write cannot be completed. Implementations
        must not leave a partial object behind on failure — a half-written
        avatar that `exists` reports as present is worse than no avatar.
        """
        ...

    async def delete(self, key: str) -> None:
        """Removes the object at `key`.

        **Idempotent.** Deleting a key that does not exist is a success,
        not an error, and every provider must honour that. The reason is
        concrete: `AvatarService.delete` removes an original and a
        thumbnail, and a crash between the two must leave the operation
        safely repeatable. If a missing object raised, the retry that
        cleans up the survivor would fail on the one already gone.

        Raises `StorageError` only when the object exists and cannot be
        removed.
        """
        ...

    async def exists(self, key: str) -> bool:
        """Whether an object is stored at `key`.

        Returns `False` rather than raising for a missing object — absence
        is the ordinary answer to this question, and a caller forced to
        catch an exception to learn it would eventually catch too much.

        Deliberately **not** used as a guard before `save`: a check-then-act
        across two round trips is a race on any store, and the platform's
        keys are random enough that a collision is not a scenario worth
        defending. It exists for verification — a cleanup job confirming an
        orphan, a test asserting a delete really happened.
        """
        ...

    def get_public_url(self, key: str) -> str:
        """The URL a browser can fetch this object from.

        **Synchronous**, unlike the other three, and the asymmetry is
        deliberate: every provider on the shortlist computes this by string
        composition from configuration, with no I/O at all. Making it
        `async` would put an `await` on every profile render to buy nothing,
        and would prevent it being called from a Pydantic serialiser.

        The consequence is stated rather than hidden: a provider whose URLs
        require a *signed* request — a private bucket with presigned URLs —
        cannot implement this method as written, because signing needs
        credentials and an expiry and is properly an async operation.
        Avatars are public objects on this platform, so that provider is
        not in scope; if one is ever needed, this port gains a second
        method rather than this one becoming async and forcing every caller
        to change.

        Does not check that the object exists, and must not: a caller
        holding a key already knows it stored one, and an existence check
        per rendered avatar would put a store round trip on every profile
        page.
        """
        ...


__all__ = [
    "KEY_SEPARATOR",
    "StorageError",
    "StorageProvider",
    "TransientInfrastructureError",
]
