"""create auth user_sessions table

Revision ID: 00debbb7452d
Revises: 31528456f438
Create Date: 2026-08-01 02:26:42.991993

The first table the `auth` module owns, and the first use of the `auth`
schema — database.md §3.1 calls it "the most sensitive schema on the
platform", and this is why.

Autogenerated, then adjusted — database.md §16: "Autogenerate is a draft,
never a commit." Alembic produced the table, the named constraints, the
foreign key and the indexes correctly. The same three omissions that
`7ed700e67f2a` documents apply again, and each breaks the migration on
its own:

1. **`CREATE SCHEMA auth`.** Alembic detects tables in a non-default
   schema but never creates the schema, so `upgrade()` failed outright on
   a clean database.

2. **Explicit enum lifecycle.** `DROP TABLE` does not drop the enum type
   the table used, so the autogenerated `downgrade()` left
   `auth.session_revoke_reason` behind and the next `upgrade()` died with
   "type already exists" — a migration that only works once is not
   reversible.

3. **`DROP SCHEMA` on the way down**, so a full downgrade returns the
   database to empty rather than leaving an orphan schema.

Verified by running upgrade -> downgrade -> upgrade against real
PostgreSQL 17 and inspecting the catalogue at each step.

**On the cross-schema foreign key.** `auth.user_sessions.user_id`
references `users.user.id`, which DB-03 forbids between module schemas.
That deviation is argued in `app/modules/auth/infrastructure/models.py`
— in short, the boundary is already collapsed by A64-010's documented
merge of `auth.account` into `users.user`, and `ON DELETE CASCADE` is
what stops a deleted account from leaving behind a live credential.
Ordering matters here: this migration must run *after* the `users` schema
exists, which `down_revision` guarantees.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op
from app.database.types import UtcDateTime

# revision identifiers, used by Alembic.
revision: str = "00debbb7452d"
down_revision: str | None = "31528456f438"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None

SCHEMA = "auth"
TABLE = "user_sessions"

# `create_type=False`: this migration manages the type's lifecycle
# explicitly (see the module docstring), so SQLAlchemy must not also emit
# a `CREATE TYPE` when the column is rendered.
revoke_reason_enum = postgresql.ENUM(
    "player",
    "password_change",
    "suspension",
    "reuse_detected",
    "expired",
    name="session_revoke_reason",
    schema=SCHEMA,
    create_type=False,
)


def upgrade() -> None:
    op.execute(f"CREATE SCHEMA IF NOT EXISTS {SCHEMA}")
    revoke_reason_enum.create(op.get_bind(), checkfirst=True)

    op.create_table(
        TABLE,
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("refresh_token_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column("token_family", sa.Uuid(), nullable=False),
        sa.Column("expires_at", UtcDateTime(), nullable=False),
        sa.Column("last_used_at", UtcDateTime(), nullable=False),
        sa.Column("device_name", sa.String(length=120), nullable=True),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("revoked_at", UtcDateTime(), nullable=True),
        sa.Column("revoked_reason", revoke_reason_enum, nullable=True),
        sa.Column("created_at", UtcDateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "(revoked_at IS NULL) = (revoked_reason IS NULL)",
            name=op.f("ck_user_sessions__revocation_is_complete"),
        ),
        sa.CheckConstraint(
            "expires_at > created_at", name=op.f("ck_user_sessions__expiry_after_creation")
        ),
        sa.CheckConstraint(
            "octet_length(refresh_token_hash) = 32",
            name=op.f("ck_user_sessions__refresh_token_hash_length"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user.id"],
            name=op.f("fk_user_sessions__user_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_sessions")),
        schema=SCHEMA,
    )
    op.create_index(
        "ix_user_sessions__token_family", TABLE, ["token_family"], unique=False, schema=SCHEMA
    )
    op.create_index(
        "ix_user_sessions__user_id_revoked_at",
        TABLE,
        ["user_id", "revoked_at", "created_at"],
        unique=False,
        schema=SCHEMA,
    )
    op.create_index(
        "uq_user_sessions__refresh_token_hash",
        TABLE,
        ["refresh_token_hash"],
        unique=True,
        schema=SCHEMA,
    )


def downgrade() -> None:
    # Reversible, and lossy in the way dropping a credential table always
    # is: every session is forgotten, so every client must sign in again.
    # That fails *closed* — nobody keeps access they should not have —
    # which is the correct direction for a rollback of an auth table.
    op.drop_index("uq_user_sessions__refresh_token_hash", table_name=TABLE, schema=SCHEMA)
    op.drop_index("ix_user_sessions__user_id_revoked_at", table_name=TABLE, schema=SCHEMA)
    op.drop_index("ix_user_sessions__token_family", table_name=TABLE, schema=SCHEMA)
    op.drop_table(TABLE, schema=SCHEMA)

    revoke_reason_enum.drop(op.get_bind(), checkfirst=True)
    # No CASCADE: if anything unexpected still lives in this schema the
    # drop should fail loudly rather than silently destroy it.
    op.execute(f"DROP SCHEMA IF EXISTS {SCHEMA}")
