"""create analytics event store

A64-027.2 — the storage half of `docs/01-architecture/analytics.md`.

Two tables in a new `analytics` schema, and the split between them is the
privacy design rather than normalisation:

    analytics.subject   player_id -> subject_key. The **only** link between
                        a person and their analytics history, and the one
                        row erasure deletes (D3)
    analytics.event     one row per fact. Carries `subject_key` and never a
                        `player_id`, so the raw store cannot be joined to
                        the product database by primary key

The autogenerated draft also proposed dropping two `users` search indexes
and clearing four unrelated server defaults — pre-existing model/database
drift that has nothing to do with this change. Removed by hand: a migration
that quietly alters a table it was not written for is the kind that is
discovered during a rollback.

**No foreign key from `event.subject_key` to `subject`.** Deliberate, and it
is the erasure semantics: `CASCADE` would delete a person's events with
their link, `RESTRICT` would make erasure fail, and `SET NULL` would destroy
the grouping that keeps aggregates correct. Rows outliving the link that
named them is the point.

Revision ID: 36f40253b8c7
Revises: f6b3d20a91c4
Create Date: 2026-09-05
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op
from app.database.types import UtcDateTime

revision: str = "36f40253b8c7"
down_revision: str | None = "f6b3d20a91c4"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None

SCHEMA = "analytics"


def upgrade() -> None:
    op.execute(f"CREATE SCHEMA IF NOT EXISTS {SCHEMA}")

    op.create_table(
        "subject",
        sa.Column("player_id", sa.Uuid(), nullable=False),
        sa.Column("subject_key", sa.Uuid(), nullable=False),
        sa.Column("is_synthetic", sa.Boolean(), nullable=False),
        sa.Column("created_at", UtcDateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("player_id", name=op.f("pk_subject")),
        sa.UniqueConstraint("subject_key", name=op.f("uq_subject__subject_key")),
        schema=SCHEMA,
    )

    op.create_table(
        "event",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("event_name", sa.String(length=64), nullable=False),
        sa.Column("event_version", sa.Integer(), nullable=False),
        sa.Column("occurred_at", UtcDateTime(), nullable=False),
        sa.Column("received_at", UtcDateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("environment", sa.String(length=16), nullable=False),
        sa.Column("subject_key", sa.Uuid(), nullable=True),
        sa.Column("anonymous_id", sa.Uuid(), nullable=True),
        sa.Column("session_id", sa.Uuid(), nullable=True),
        sa.Column("is_synthetic", sa.Boolean(), nullable=False),
        sa.Column("properties", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_event_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "event_version >= 1",
            name=op.f("ck_event__ck_analytics_event__version_positive"),
        ),
        # The primary key **is** the deduplication mechanism. A redelivered
        # outbox event derives the same id and conflicts; `ON CONFLICT DO
        # NOTHING` then makes at-least-once delivery an exactly-once effect
        # without depending on transaction ordering or on two workers not
        # racing.
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event")),
        schema=SCHEMA,
    )

    # Every metric filters on environment and name over a window.
    op.create_index(
        "ix_analytics_event__environment_name_occurred",
        "event",
        ["environment", "event_name", "occurred_at"],
        unique=False,
        schema=SCHEMA,
    )
    # Retention, activation and per-player counts walk one subject in order.
    # Partial, so the anonymous half of the table carries no entries.
    op.create_index(
        "ix_analytics_event__subject_occurred",
        "event",
        ["subject_key", "occurred_at"],
        unique=False,
        schema=SCHEMA,
        postgresql_where=sa.text("subject_key IS NOT NULL"),
    )
    # The acquisition funnel walks one browser. Partial for the inverse
    # reason: an authenticated product event has no anonymous id.
    op.create_index(
        "ix_analytics_event__anonymous_occurred",
        "event",
        ["anonymous_id", "occurred_at"],
        unique=False,
        schema=SCHEMA,
        postgresql_where=sa.text("anonymous_id IS NOT NULL"),
    )
    # The retention prune's only predicate, and the leading column of the
    # partition key this table will eventually have.
    op.create_index(
        "ix_analytics_event__occurred_at",
        "event",
        ["occurred_at"],
        unique=False,
        schema=SCHEMA,
    )


def downgrade() -> None:
    op.drop_index("ix_analytics_event__occurred_at", table_name="event", schema=SCHEMA)
    op.drop_index(
        "ix_analytics_event__anonymous_occurred",
        table_name="event",
        schema=SCHEMA,
        postgresql_where=sa.text("anonymous_id IS NOT NULL"),
    )
    op.drop_index(
        "ix_analytics_event__subject_occurred",
        table_name="event",
        schema=SCHEMA,
        postgresql_where=sa.text("subject_key IS NOT NULL"),
    )
    op.drop_index(
        "ix_analytics_event__environment_name_occurred", table_name="event", schema=SCHEMA
    )
    op.drop_table("event", schema=SCHEMA)
    op.drop_table("subject", schema=SCHEMA)
    op.execute(f"DROP SCHEMA IF EXISTS {SCHEMA}")
