"""tighten username length to 20

Revision ID: 3caf68aa8cfc
Revises: 7ed700e67f2a
Create Date: 2026-08-01 00:43:12.553627

Autogenerated, then adjusted — database.md §16: "Autogenerate is a draft,
never a commit."

Alembic detected both `VARCHAR(32) -> VARCHAR(20)` column changes (thanks
to `compare_type=True`, set in `env.py` for exactly this reason). What it
did **not** detect is the `ck_user__username_length` CHECK constraint,
which still reads `BETWEEN 3 AND 32`: Alembic does not compare check
constraints at all, so an autogenerated-and-accepted migration would have
left the database enforcing the old bound while the application enforced
the new one. That is the silent half-migration BE-06 cares about — the
constraint is the authoritative guard, so leaving it stale means the
guard and the domain disagree.

The constraint is therefore dropped and recreated by hand, in both
directions.

**The generated column has to be demolished and rebuilt.** PostgreSQL
refuses `ALTER COLUMN username TYPE ...` outright while `username_folded`
exists, with `cannot alter type of a column used by a generated column` —
a generated column's expression pins the type of everything it reads.
Alembic's autogenerated `alter_column` pair therefore cannot work here at
all, in either direction. The sequence has to be: drop the dependent
generated column (which takes its unique index with it), widen or narrow
`username`, then recreate the generated column and its index.

That also means this migration briefly drops `uq_user__username_folded`,
the constraint enforcing case-insensitive username uniqueness (UP-1). It
is inside one transaction, so no window exists where a concurrent writer
could slip a duplicate in — PostgreSQL's DDL is transactional, and this
is one of the places that property is doing real work rather than being
a nicety.

**Ordering matters.** The CHECK is dropped first and recreated last,
because PostgreSQL validates a new CHECK against existing rows and a
stale bound would contradict the new column width in between.

**`op.f()` around the constraint name is load-bearing.** Without it,
Alembic runs the name through `Base.metadata`'s naming convention
(`ck_%(table_name)s__%(constraint_name)s`, database.md §2) and produces
`ck_user__ck_user__username_length` — a double prefix that matches
nothing, so the migration dies on `constraint ... does not exist`.
`op.f()` marks a name as already-final. Any future migration touching a
named constraint needs the same treatment; the trap is that it fails only
at run time, never at import or review.

**Data safety.** `VARCHAR(32) -> VARCHAR(20)` fails outright if any row
holds a longer value, and hyphenated usernames (permitted before this
revision, not after) would also become unreachable through the
application. Neither case exists — the table is empty in every
environment — but a future run against real data needs a backfill first,
which is why this is stated rather than assumed.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3caf68aa8cfc"
down_revision: str | None = "7ed700e67f2a"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None

SCHEMA = "users"
CHECK_NAME = "ck_user__username_length"
FOLDED_INDEX = "uq_user__username_folded"
FOLD_EXPRESSION = "lower(normalize(username, NFKC))"


def _resize_username(*, new_length: int, old_length: int, check_upper_bound: int) -> None:
    """One routine for both directions — they differ only in the numbers.

    Written once rather than twice because a downgrade that is a
    hand-mirrored copy of an upgrade is where the two silently stop
    matching, and this migration's whole risk is in the *sequence*, not
    the values.
    """
    op.drop_constraint(op.f(CHECK_NAME), "user", schema=SCHEMA, type_="check")

    # Dropping the generated column also drops `uq_user__username_folded`,
    # which is defined over it — recreated explicitly below.
    op.drop_column("user", "username_folded", schema=SCHEMA)

    op.alter_column(
        "user",
        "username",
        existing_type=sa.VARCHAR(length=old_length),
        type_=sa.String(length=new_length),
        existing_nullable=False,
        schema=SCHEMA,
    )

    op.add_column(
        "user",
        sa.Column(
            "username_folded",
            sa.String(length=new_length),
            sa.Computed(FOLD_EXPRESSION, persisted=True),
            nullable=False,
        ),
        schema=SCHEMA,
    )
    op.create_index(FOLDED_INDEX, "user", ["username_folded"], unique=True, schema=SCHEMA)

    op.create_check_constraint(
        op.f(CHECK_NAME),
        "user",
        f"char_length(username) BETWEEN 3 AND {check_upper_bound}",
        schema=SCHEMA,
    )


def upgrade() -> None:
    _resize_username(new_length=20, old_length=32, check_upper_bound=20)


def downgrade() -> None:
    _resize_username(new_length=32, old_length=20, check_upper_bound=32)
