"""create auth password reset tokens

Revision ID: 68e5e310737a
Revises: 743c389240a8
Create Date: 2026-08-01 03:58:46.514320

database.md §4.5's `auth.password_reset_token`, under the name the task
gives it.

**Autogenerated and correct as generated**, for the same three reasons
`743c389240a8` was: the `auth` schema already exists (created by the
`user_sessions` migration, which this one is ordered after), there is no
enum type whose lifecycle Alembic would ignore, and the partial index's
`WHERE used_at IS NULL` predicate came through intact. Only the docstring
and formatting are hand-written.

`DROP SCHEMA` is deliberately **absent** from `downgrade`: `auth` still
holds `user_sessions` and `email_verification_tokens`, and dropping it
here would destroy two unrelated tables.

## The partial unique index is the load-bearing one

`uq_password_reset_tokens__one_live_per_user` enforces §4.5's "at most one
live token per account" in the database rather than in the service. Two
concurrent forgot-password requests both pass a check-then-act; only this
index is correct under concurrency (BE-06). It is what turns "issuing a
new link invalidates the old one" from an intention into a guarantee.

That matters more here than on the verification table. What a lost race
leaves alive there is a link that confirms an address; what it leaves
alive here is a working password reset for an account whose owner has
already asked for a new one — which is exactly the token a person would
have if they had intercepted the *first* email and were waiting.

Its predicate is `used_at IS NULL` and not "unused and unexpired", though
the doc phrases it the second way: `now()` is not immutable, so PostgreSQL
refuses it in an index predicate. Expired tokens are marked used by the
service, which this index does see.

Verified by running upgrade -> downgrade -> upgrade against real
PostgreSQL 17 and inspecting the catalogue at each step.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from app.database.types import UtcDateTime

# revision identifiers, used by Alembic.
revision: str = "68e5e310737a"
down_revision: str | None = "743c389240a8"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None

SCHEMA = "auth"
TABLE = "password_reset_tokens"


def upgrade() -> None:
    op.create_table(
        TABLE,
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column("expires_at", UtcDateTime(), nullable=False),
        sa.Column("used_at", UtcDateTime(), nullable=True),
        sa.Column("created_at", UtcDateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "expires_at > created_at",
            name=op.f("ck_password_reset_tokens__expiry_after_creation"),
        ),
        sa.CheckConstraint(
            "octet_length(token_hash) = 32",
            name=op.f("ck_password_reset_tokens__token_hash_length"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user.id"],
            name=op.f("fk_password_reset_tokens__user_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_password_reset_tokens")),
        schema=SCHEMA,
    )
    op.create_index(
        "ix_password_reset_tokens__expires_at",
        TABLE,
        ["expires_at"],
        unique=False,
        schema=SCHEMA,
    )
    op.create_index(
        "ix_password_reset_tokens__user_id",
        TABLE,
        ["user_id"],
        unique=False,
        schema=SCHEMA,
    )
    op.create_index(
        "uq_password_reset_tokens__one_live_per_user",
        TABLE,
        ["user_id"],
        unique=True,
        schema=SCHEMA,
        postgresql_where=sa.text("used_at IS NULL"),
    )
    op.create_index(
        "uq_password_reset_tokens__token_hash",
        TABLE,
        ["token_hash"],
        unique=True,
        schema=SCHEMA,
    )


def downgrade() -> None:
    # Reversible, and lossy in the way dropping a credential table always
    # is: every outstanding reset link stops working, so anyone
    # mid-recovery asks for a new one. That fails *closed* — nobody's
    # password is replaced who should not have replaced it — which is the
    # correct direction.
    op.drop_index("uq_password_reset_tokens__token_hash", table_name=TABLE, schema=SCHEMA)
    op.drop_index(
        "uq_password_reset_tokens__one_live_per_user",
        table_name=TABLE,
        schema=SCHEMA,
        postgresql_where=sa.text("used_at IS NULL"),
    )
    op.drop_index("ix_password_reset_tokens__user_id", table_name=TABLE, schema=SCHEMA)
    op.drop_index("ix_password_reset_tokens__expires_at", table_name=TABLE, schema=SCHEMA)
    op.drop_table(TABLE, schema=SCHEMA)
    # No `DROP SCHEMA`: `auth.user_sessions` and
    # `auth.email_verification_tokens` still live here.
