"""create auth email verification tokens

Revision ID: 743c389240a8
Revises: 7989d2c17008
Create Date: 2026-08-01 03:29:15.074241

database.md §4.5's `auth.email_verification`, under the name the task
gives it.

**Autogenerated and, unusually, correct as generated.** The three
omissions that broke `7ed700e67f2a` and `00debbb7452d` do not apply here:
the `auth` schema already exists (created by the `user_sessions`
migration, which this one is ordered after), there is no enum type whose
lifecycle Alembic would ignore, and the partial index's `WHERE used_at IS
NULL` predicate came through intact. Only the docstring and formatting
are hand-written.

`DROP SCHEMA` is deliberately **absent** from `downgrade`, unlike the two
earlier migrations: `auth.user_sessions` still lives in this schema, so
dropping it here would destroy an unrelated table.

## The partial unique index is the load-bearing one

`uq_email_verification_tokens__one_live_per_user` enforces §4.5's "at
most one live token per account" in the database rather than in the
service. Two concurrent resends both pass a check-then-act; only this
index is correct under concurrency (BE-06). It is what turns "invalidate
the previous token" from an intention into a guarantee.

Its predicate is `used_at IS NULL` and not "unused and unexpired",
though the doc phrases it the second way: `now()` is not immutable, so
PostgreSQL refuses it in an index predicate. Expired tokens are marked
used by the service, which this index does see.

Verified by running upgrade -> downgrade -> upgrade against real
PostgreSQL 17 and inspecting the catalogue at each step.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from app.database.types import UtcDateTime

# revision identifiers, used by Alembic.
revision: str = "743c389240a8"
down_revision: str | None = "7989d2c17008"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None

SCHEMA = "auth"
TABLE = "email_verification_tokens"


def upgrade() -> None:
    op.create_table(
        TABLE,
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column("expires_at", UtcDateTime(), nullable=False),
        sa.Column("used_at", UtcDateTime(), nullable=True),
        sa.Column("created_at", UtcDateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "expires_at > created_at",
            name=op.f("ck_email_verification_tokens__expiry_after_creation"),
        ),
        sa.CheckConstraint(
            "octet_length(token_hash) = 32",
            name=op.f("ck_email_verification_tokens__token_hash_length"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user.id"],
            name=op.f("fk_email_verification_tokens__user_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email_verification_tokens")),
        schema=SCHEMA,
    )
    op.create_index(
        "ix_email_verification_tokens__expires_at",
        TABLE,
        ["expires_at"],
        unique=False,
        schema=SCHEMA,
    )
    op.create_index(
        "ix_email_verification_tokens__user_id",
        TABLE,
        ["user_id"],
        unique=False,
        schema=SCHEMA,
    )
    op.create_index(
        "uq_email_verification_tokens__one_live_per_user",
        TABLE,
        ["user_id"],
        unique=True,
        schema=SCHEMA,
        postgresql_where=sa.text("used_at IS NULL"),
    )
    op.create_index(
        "uq_email_verification_tokens__token_hash",
        TABLE,
        ["token_hash"],
        unique=True,
        schema=SCHEMA,
    )


def downgrade() -> None:
    # Reversible, and lossy in the way dropping a credential table always
    # is: every outstanding verification link stops working, so anyone
    # mid-verification asks for a new one. That fails *closed* — nobody
    # becomes verified who should not be — which is the correct direction.
    op.drop_index("uq_email_verification_tokens__token_hash", table_name=TABLE, schema=SCHEMA)
    op.drop_index(
        "uq_email_verification_tokens__one_live_per_user",
        table_name=TABLE,
        schema=SCHEMA,
        postgresql_where=sa.text("used_at IS NULL"),
    )
    op.drop_index("ix_email_verification_tokens__user_id", table_name=TABLE, schema=SCHEMA)
    op.drop_index("ix_email_verification_tokens__expires_at", table_name=TABLE, schema=SCHEMA)
    op.drop_table(TABLE, schema=SCHEMA)
    # No `DROP SCHEMA`: `auth.user_sessions` still lives here.
