"""add rotated session revoke reason

Revision ID: 7989d2c17008
Revises: 00debbb7452d
Create Date: 2026-08-01 03:04:08.304381

A64-011.4 declared `RevocationReason` without a `rotated` member, on the
grounds that nothing rotated yet and an unused member on a security enum
reads as wired-up. A64-011.5 implements rotation, so it arrives with its
caller.

**Written by hand — `alembic revision` without `--autogenerate`.** Alembic
does not detect enum *value* additions at all: autogenerate compares
tables, indexes and constraints, and a new label on an existing type is
none of those. Verified directly while building this: the autogenerated
revision was an empty `pass`, and `alembic check` reported no drift while
the enum was still missing the value. Silent rather than wrong, which is
worse — the first rotation in production would raise `invalid input value
for enum`.

`ADD VALUE` cannot be used later in the same transaction block that
creates it. Nothing here does, so the plain statement is safe, and
`IF NOT EXISTS` makes a re-run a no-op rather than an error.

## Why `downgrade` does not remove the value

PostgreSQL has no `DROP VALUE`. Removing a label means recreating the type
and rewriting every column that uses it, which on a credential table is a
lock this platform will not take for a rollback (DB-05: no long locks on
the permanent record). The downgrade instead rewrites any `rotated` rows
to `player` — the closest surviving meaning, since both describe a
session deliberately ended and neither is a security event — so the older
code, which has never heard of `rotated`, can still read every row.

Lossy, and deliberately so: the alternative is a downgrade that leaves
rows the previous version crashes on.
"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7989d2c17008"
down_revision: str | None = "00debbb7452d"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None

ENUM = "auth.session_revoke_reason"


def upgrade() -> None:
    op.execute(f"ALTER TYPE {ENUM} ADD VALUE IF NOT EXISTS 'rotated'")


def downgrade() -> None:
    # See the module docstring: the label stays, the rows are remapped so
    # the previous version can read them.
    #
    # `revoked_reason::text = 'rotated'` rather than the bare enum literal,
    # and that is not style. A bare `= 'rotated'` is parsed as an enum
    # literal, so PostgreSQL rejects the *whole statement* with "invalid
    # input value for enum" whenever the label is absent — which is
    # precisely the state a downgrade can find itself in if the upgrade
    # never ran. Observed directly: `alembic downgrade -1` failed against a
    # database whose enum had never gained the value, leaving the version
    # table pointing at a revision whose effects were not applied. Casting
    # to text makes the comparison a string comparison that is always
    # legal, so the downgrade is safe from any state.
    op.execute(
        "UPDATE auth.user_sessions SET revoked_reason = 'player' "
        "WHERE revoked_reason::text = 'rotated'"
    )
