"""create users user table

Revision ID: 7ed700e67f2a
Revises:
Create Date: 2026-08-01 00:11:33.643750

Autogenerated, then adjusted — database.md §16: "Autogenerate is a draft,
never a commit." Alembic produced the table, the computed column, the
named constraints and the indexes correctly. Three things it does not
emit, each of which breaks this migration on its own, were added by hand:

1. **`CREATE SCHEMA users`.** Alembic detects tables in a non-default
   schema but never creates the schema itself, so the autogenerated
   `upgrade()` failed outright on a clean database.

2. **Explicit enum lifecycle.** `DROP TABLE` in PostgreSQL does *not*
   drop an enum type the table used. The autogenerated `downgrade()`
   therefore left `users.locale` behind, and the next `upgrade()` died
   with "type already exists" — a migration that only works once is not
   reversible. The type is now created and dropped explicitly, with
   `create_type=False` on the column so SQLAlchemy does not also try to
   create it implicitly and conflict.

3. **`DROP SCHEMA` on the way down**, so a full downgrade genuinely
   returns the database to empty rather than leaving an orphan schema.

Verified by running upgrade -> downgrade -> upgrade -> downgrade against
real PostgreSQL 17 and inspecting the catalogue at each step.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op
from app.database.types import UtcDateTime

# revision identifiers, used by Alembic.
revision: str = "7ed700e67f2a"
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None

SCHEMA = "users"

# `create_type=False`: this migration manages the type's lifecycle
# explicitly (see the module docstring), so SQLAlchemy must not also
# emit a `CREATE TYPE` when the column is rendered.
locale_enum = postgresql.ENUM("en", "ru", "uz", name="locale", schema=SCHEMA, create_type=False)


def upgrade() -> None:
    op.execute(f"CREATE SCHEMA IF NOT EXISTS {SCHEMA}")
    locale_enum.create(op.get_bind(), checkfirst=True)

    op.create_table(
        "user",
        sa.Column("username", sa.String(length=32), nullable=False),
        sa.Column(
            "username_folded",
            sa.String(length=32),
            sa.Computed("lower(normalize(username, NFKC))", persisted=True),
            nullable=False,
        ),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("preferred_language", locale_enum, server_default="en", nullable=False),
        sa.Column("timezone", sa.String(length=64), server_default="UTC", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("is_verified", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("display_name", sa.String(length=64), nullable=True),
        sa.Column("avatar_url", sa.String(length=2048), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", UtcDateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", UtcDateTime(), nullable=True),
        sa.CheckConstraint("char_length(email) > 0", name=op.f("ck_user__email_not_empty")),
        sa.CheckConstraint(
            "char_length(username) BETWEEN 3 AND 32", name=op.f("ck_user__username_length")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
        schema=SCHEMA,
    )
    op.create_index(
        "ix_user__created_at_id", "user", ["created_at", "id"], unique=False, schema=SCHEMA
    )
    op.create_index("uq_user__email", "user", ["email"], unique=True, schema=SCHEMA)
    op.create_index(
        "uq_user__username_folded", "user", ["username_folded"], unique=True, schema=SCHEMA
    )


def downgrade() -> None:
    op.drop_index("uq_user__username_folded", table_name="user", schema=SCHEMA)
    op.drop_index("uq_user__email", table_name="user", schema=SCHEMA)
    op.drop_index("ix_user__created_at_id", table_name="user", schema=SCHEMA)
    op.drop_table("user", schema=SCHEMA)

    locale_enum.drop(op.get_bind(), checkfirst=True)
    # No CASCADE: if anything unexpected still lives in this schema the
    # drop should fail loudly rather than silently destroy it.
    op.execute(f"DROP SCHEMA IF EXISTS {SCHEMA}")
