"""add rating persistence

A64-017.2, SPEC-RATING §10. Two relations and their enums:

    rating.player_rating       one row per (player, variant, speed class)
    rating.rating_adjustment   one row per (player, match) — permanent

Hand-written rather than autogenerated. Autogenerate on this repository
also reports two `users` trigram indexes as removals (they are expression
indexes attached by `register_search_ddl`, which metadata cannot model) and
the contract suite's own fixture table — neither of which belongs in a
migration. `tests/contract/test_schema_drift.py` is what proves this file
and the models agree.

Revision ID: a3c1d9f47b20
Revises: 076977bf9233
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op
from app.database.types import UtcDateTime

revision: str = "a3c1d9f47b20"
down_revision: str | None = "076977bf9233"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_SCHEMA = "rating"

#: `rating` declares its own enum types rather than borrowing `game`'s —
#: the pattern `matchmaking.queue_variant` already established. Sharing one
#: across schemas would make a variant added by `game` a migration that
#: locks this context's tables too.
#: `create_type=False`, because the types are created once explicitly
#: below. Without it `create_table` would emit `CREATE TYPE` again for the
#: second table and fail on the duplicate.
_VARIANT = postgresql.ENUM("russian_8x8", name="rating_variant", schema=_SCHEMA, create_type=False)

#: All five members from day one, though SPEC-RATING §8 makes only
#: `classical` reachable in v0.5.0. Adding an enum member later is a
#: migration of a permanent competitive record; carrying five costs nothing.
_SPEED_CLASS = postgresql.ENUM(
    "bullet",
    "blitz",
    "rapid",
    "classical",
    "correspondence",
    name="rating_speed_class",
    schema=_SCHEMA,
    create_type=False,
)


def upgrade() -> None:
    op.execute(sa.schema.CreateSchema(_SCHEMA, if_not_exists=True))

    bind = op.get_bind()
    _VARIANT.create(bind, checkfirst=True)
    _SPEED_CLASS.create(bind, checkfirst=True)

    op.create_table(
        "player_rating",
        sa.Column("player_id", sa.UUID(), nullable=False),
        sa.Column("variant", _VARIANT, nullable=False),
        sa.Column("speed_class", _SPEED_CLASS, nullable=False),
        sa.Column("rating_value", sa.Float(), nullable=False),
        sa.Column("rating_deviation", sa.Float(), nullable=False),
        sa.Column("rating_volatility", sa.Float(), nullable=False),
        sa.Column("games_played", sa.Integer(), nullable=False),
        sa.Column("is_frozen", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("peak_value", sa.Float(), nullable=True),
        sa.Column("peak_at", UtcDateTime(), nullable=True),
        sa.Column("last_rated_at", UtcDateTime(), nullable=True),
        sa.Column("season_id", sa.UUID(), nullable=True),
        sa.Column("created_at", UtcDateTime(), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", UtcDateTime(), nullable=True),
        sa.PrimaryKeyConstraint(
            "player_id", "variant", "speed_class", name=op.f("pk_player_rating")
        ),
        # BE-06 — each restates a check the aggregate performs, so a row
        # written by a backfill cannot be inconsistent either.
        sa.CheckConstraint("games_played >= 0", name=op.f("ck_player_rating__games_not_negative")),
        sa.CheckConstraint(
            "rating_deviation > 0", name=op.f("ck_player_rating__deviation_positive")
        ),
        sa.CheckConstraint(
            "rating_volatility > 0", name=op.f("ck_player_rating__volatility_positive")
        ),
        sa.CheckConstraint(
            "peak_value IS NULL OR peak_value >= rating_value",
            name=op.f("ck_player_rating__peak_is_a_peak"),
        ),
        sa.CheckConstraint(
            "(peak_value IS NULL) = (peak_at IS NULL)",
            name=op.f("ck_player_rating__peak_is_complete"),
        ),
        sa.CheckConstraint(
            "(games_played = 0) = (last_rated_at IS NULL)",
            name=op.f("ck_player_rating__played_iff_rated_at"),
        ),
        schema=_SCHEMA,
    )

    # The leaderboard's whole query — SPEC-RATING §15. Descending, because
    # every reader of a rating reads it from the top.
    # The leaderboard's ordering, exactly — A64-017.4. See the model for
    # why `rating_deviation` is in it and why the index is not unique.
    op.create_index(
        "ix_player_rating__standings",
        "player_rating",
        [
            "variant",
            "speed_class",
            sa.text("rating_value DESC"),
            "rating_deviation",
            "player_id",
        ],
        schema=_SCHEMA,
    )

    op.create_table(
        "rating_adjustment",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("player_id", sa.UUID(), nullable=False),
        sa.Column("match_id", sa.UUID(), nullable=False),
        sa.Column("variant", _VARIANT, nullable=False),
        sa.Column("speed_class", _SPEED_CLASS, nullable=False),
        sa.Column("rating_before", sa.Float(), nullable=False),
        sa.Column("deviation_before", sa.Float(), nullable=False),
        sa.Column("volatility_before", sa.Float(), nullable=False),
        sa.Column("rating_after", sa.Float(), nullable=False),
        sa.Column("deviation_after", sa.Float(), nullable=False),
        sa.Column("volatility_after", sa.Float(), nullable=False),
        sa.Column("opponent_rating", sa.Float(), nullable=False),
        sa.Column("opponent_deviation", sa.Float(), nullable=False),
        sa.Column("opponent_volatility", sa.Float(), nullable=False),
        sa.Column("expected_score", sa.Float(), nullable=False),
        sa.Column("actual_score", sa.Float(), nullable=False),
        sa.Column("algorithm_version", sa.String(length=64), nullable=False),
        sa.Column("applied_at", UtcDateTime(), nullable=False),
        sa.Column("season_id", sa.UUID(), nullable=True),
        sa.Column("created_at", UtcDateTime(), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", UtcDateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rating_adjustment")),
        # **PR-1's exactly-once mechanism.** Two columns rather than three:
        # a match belongs to exactly one key, so this is strictly stronger
        # than including it — a three-column index would permit two
        # adjustments for one player and one match under different keys.
        sa.UniqueConstraint("player_id", "match_id", name="uq_rating_adjustment__player_match"),
        sa.ForeignKeyConstraint(
            ["player_id", "variant", "speed_class"],
            [
                f"{_SCHEMA}.player_rating.player_id",
                f"{_SCHEMA}.player_rating.variant",
                f"{_SCHEMA}.player_rating.speed_class",
            ],
            name="fk_rating_adjustment__player_rating",
            # No cascade: deleting a rating must not silently delete the
            # record of how it got there.
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(
            "actual_score IN (0, 0.5, 1)", name=op.f("ck_rating_adjustment__score_is_a_result")
        ),
        sa.CheckConstraint(
            "expected_score > 0 AND expected_score < 1",
            name=op.f("ck_rating_adjustment__expectation_is_a_probability"),
        ),
        schema=_SCHEMA,
    )

    op.create_index(
        "ix_rating_adjustment__player_history",
        "rating_adjustment",
        ["player_id", "variant", "speed_class", sa.text("applied_at DESC")],
        schema=_SCHEMA,
    )

    # The seat rating snapshots — SPEC-RATING §7.6, MT-4. On `game.match`
    # because they are a fact about the match, written once by
    # `matchmaking` through `CreateMatchRequest` and never updated.
    #
    # **No foreign key to `rating.player_rating`**: a seat is a snapshot of
    # a past value, not a reference to a live row that would move under it —
    # which is precisely what PR-3 forbids.
    #
    # Nullable because every match created before this migration has none.
    # Null means "created before ratings existed", and such a match cannot
    # be rated, which is correct: nothing rated it.
    for side in ("light", "dark"):
        op.add_column(
            "match", sa.Column(f"{side}_rating_value", sa.Float(), nullable=True), schema="game"
        )
        op.add_column(
            "match", sa.Column(f"{side}_rating_deviation", sa.Float(), nullable=True), schema="game"
        )
        op.add_column(
            "match",
            sa.Column(f"{side}_rating_volatility", sa.Float(), nullable=True),
            schema="game",
        )
        op.add_column(
            "match", sa.Column(f"{side}_rating_games", sa.Integer(), nullable=True), schema="game"
        )
        op.add_column(
            "match",
            sa.Column(f"{side}_rating_provisional", sa.Boolean(), nullable=True),
            schema="game",
        )

    # A `String`, not an enum type: the members belong to `rating`, and a
    # native enum in `game`'s schema would be a type `game` owns listing
    # values `rating` decides.
    op.add_column(
        "match", sa.Column("rating_speed_class", sa.String(length=24), nullable=True), schema="game"
    )


def downgrade() -> None:
    op.drop_column("match", "rating_speed_class", schema="game")
    for side in ("light", "dark"):
        for suffix in ("value", "deviation", "volatility", "games", "provisional"):
            op.drop_column("match", f"{side}_rating_{suffix}", schema="game")

    op.drop_index("ix_rating_adjustment__player_history", "rating_adjustment", schema=_SCHEMA)
    op.drop_table("rating_adjustment", schema=_SCHEMA)
    op.drop_index("ix_player_rating__standings", "player_rating", schema=_SCHEMA)
    op.drop_table("player_rating", schema=_SCHEMA)

    bind = op.get_bind()
    _SPEED_CLASS.drop(bind, checkfirst=True)
    _VARIANT.drop(bind, checkfirst=True)

    op.execute(sa.schema.DropSchema(_SCHEMA, if_exists=True))
