"""create notification broadcast

A64-027A — the storage half of `domain/broadcast.py`.

One table, `notifications.notification_broadcast`, and it is the system of
record for what an administrator told the platform. The notifications it
produces are a projection of it; this row is the answer to "who sent that,
when, and to whom", which §23 requires to outlive the inbox entries.

**No foreign key to `users`.** `created_by` is an opaque `player_id` like
every other cross-context reference in this schema (DM-06) — a foreign key
here would make `notifications` and `users` undeployable apart.

The autogenerated draft also proposed dropping two `users` search indexes
and clearing four unrelated server defaults, in `admin`, `platform` and
`tournaments`. That is pre-existing model/database drift with nothing to do
with this change, and the same drift A64-027.2's migration removed by hand
for the same reason: a migration that quietly alters tables it was not
written for is the kind that is discovered during a rollback.

Revision ID: b6e37e8af2d6
Revises: 36f40253b8c7
Create Date: 2026-09-05
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op
from app.database.types import UtcDateTime

revision: str = "b6e37e8af2d6"
down_revision: str | None = "36f40253b8c7"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None

SCHEMA = "notifications"


def upgrade() -> None:
    op.create_table(
        "notification_broadcast",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("body", sa.String(length=600), nullable=False),
        sa.Column("locale", sa.String(length=8), nullable=False),
        sa.Column("audience", sa.String(length=32), nullable=False),
        sa.Column("channel", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=64), nullable=False),
        sa.Column(
            "recipients",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        # Nullable on purpose: `NULL` means "not counted yet", and a zero
        # here would read as a broadcast that reached nobody.
        sa.Column("audience_size", sa.Integer(), nullable=True),
        sa.Column("delivered", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("created_at", UtcDateTime(), nullable=False),
        sa.Column("started_at", UtcDateTime(), nullable=True),
        sa.Column("completed_at", UtcDateTime(), nullable=True),
        sa.Column("failure_reason", sa.String(length=200), nullable=True),
        sa.Column("cursor", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_broadcast")),
        # A double-submitted composer is the same broadcast, not a second
        # one. Scoped to the administrator so two of them cannot collide on
        # a client-generated value.
        sa.UniqueConstraint(
            "created_by",
            "idempotency_key",
            name="uq_notification_broadcast__admin_key",
        ),
        schema=SCHEMA,
    )

    # The worker's claim: the oldest unfinished broadcast. Partial, so the
    # index holds only outstanding work and is empty when there is none.
    op.create_index(
        "ix_notification_broadcast__pending",
        "notification_broadcast",
        ["created_at"],
        unique=False,
        schema=SCHEMA,
        postgresql_where=sa.text("status IN ('queued', 'sending')"),
    )
    # The console's history: newest first, over everything.
    op.create_index(
        "ix_notification_broadcast__created_at_id",
        "notification_broadcast",
        [sa.literal_column("created_at DESC"), sa.literal_column("id DESC")],
        unique=False,
        schema=SCHEMA,
    )


def downgrade() -> None:
    op.drop_index(
        "ix_notification_broadcast__created_at_id",
        table_name="notification_broadcast",
        schema=SCHEMA,
    )
    op.drop_index(
        "ix_notification_broadcast__pending",
        table_name="notification_broadcast",
        schema=SCHEMA,
        postgresql_where=sa.text("status IN ('queued', 'sending')"),
    )
    op.drop_table("notification_broadcast", schema=SCHEMA)
